.PHONY: clean

lines: lines.c
	clang -Wall -g -o lines lines.c
upper: upper.c
	clang -Wall -g -o upper upper.c
lower: lower.c
	clang -Wall -o lower lower.c
title: title.c
	clang -Wall -o title title.c
wordcnt: wordcnt.c
	clang -Wall -g -o wordcnt wordcnt.c
celsius: celsius.c
	clang -Wall -g -o celsius celsius.c

clean:
	rm -rf lines lines.dSYM upper upper.dSYM lower lower.dSYM title title.dSYM wordcnt wordcnt.dSYM celsius celsius.dSYM
